spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        physical_naming_strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        enable_lazy_load_no_trans: true
hyphen:
  user_id: cgt2022
  hkey: b461bceea477f528
jusogov:
  confirm-key:
    road_addr: U01TX0FVVEgyMDI0MDcyMDIzNDYwNzExNDk0Mzg=
    road_addr_detail : U01TX0FVVEgyMDI0MDcyMDIzNDkwNTExNDk0Mzk=
vworld:
  key: E3422A28-9B67-3BCF-912F-5B7BBE6C8318
social:
  kakao:
    admin-key: 10e662095af367398e3a520930d32cfd
logging:
  level:
    org.hibernate.type.descriptor.sql: WARN
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 60000