server:
  port: 80
  tomcat:
    accesslog:
      enabled: true
      prefix: access_log
      suffix: .log
      file-date-format: .yyyy-MM-dd
      pattern: '%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i"'
      request-attributes-enabled: true

spring:
  profiles:
    group:
      "local" : "local, jwt, oauth, common"
      "dev" : "dev, jwt, oauth, common"
      "real" : "real, jwt, oauth, common"
    # active: local   #활성 프로필 설정(local, dev, real)

--- # local 설정
spring:
  config:
    activate:
      on-profile: "local"
  datasource:
    url: jdbc:log4jdbc:mysql://3.39.27.126:3306/howtaxing?useSSL=false&autoReconnect=true&autoReconnection=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul
    username: root
    password: Xmonster11@@
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    tomcat:
      max-active: 50
      max-idle: 50
      min-idle: 10
      max-wait: -1
      initial-size: 10
      test-on-borrow: true
      test-while-idle: true
      validation-query: 'select 1'
      time-between-eviction-runs-millis: 3000
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
  redis:
    host: 3.39.27.126
    port: 6379
    password: Xmonster11@@
  mvc:
    custom-uri-logging-filter:
      enabled: true
      level: debug
server:
  tomcat:
    accesslog:
      directory: D:\APP_LOG
logging:
  level:
    root: WARN
    log4jdbc.log4j2: WARN
    com.xmonster.howtaxing: DEBUG

--- # dev 설정
spring:
  config:
    activate:
      on-profile: "dev"
  datasource:
    url: jdbc:log4jdbc:mysql://3.39.27.126:3306/howtaxing?useSSL=false&autoReconnect=true&autoReconnection=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul
    username: root
    password: Xmonster11@@
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    tomcat:
      max-active: 50
      max-idle: 50
      min-idle: 10
      max-wait: -1
      initial-size: 10
      test-on-borrow: true
      test-while-idle: true
      validation-query: 'select 1'
      time-between-eviction-runs-millis: 3000
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
  redis:
    host: 172.20.0.4
    port: 6379
    password: Xmonster11@@
  mvc:
    custom-uri-logging-filter:
      enabled: true
      level: info
server:
  tomcat:
    accesslog:
      directory: /home/logs
logging:
  level:
    root: INFO
    log4jdbc.log4j2: WARN
    com.xmonster.howtaxing: DEBUG

--- # real 설정
spring:
  config:
    activate:
      on-profile: "real"
  datasource:
    url: jdbc:log4jdbc:mysql://43.201.96.165:3306/howtaxing?useSSL=false&autoReconnect=true&autoReconnection=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Seoul
    username: root
    password: Xmonster11@@
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    tomcat:
      max-active: 50
      max-idle: 50
      min-idle: 10
      max-wait: -1
      initial-size: 10
      test-on-borrow: true
      test-while-idle: true
      validation-query: 'select 1'
      time-between-eviction-runs-millis: 3000
  batch:
    jdbc:
      initialize-schema: never
    job:
      enabled: false
  redis:
    host: 172.18.0.2
    port: 6379
    password: Xmonster11@@
  mvc:
    custom-uri-logging-filter:
      enabled: true
      level: info
server:
  tomcat:
    accesslog:
      directory: /home/logs
logging:
  level:
    root: INFO
    log4jdbc.log4j2: WARN
    com.xmonster.howtaxing: INFO
