--- # local 설정
spring:
  config:
    activate:
      on-profile: "local"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 797361358853-j9mpkpnq9bgrnmahi46dgkb5loufk5bg.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email
          naver:
            client-id: orG8AAE8iHfRSoiySAbv
            client-secret: DEn_pJGqup
            redirect-uri: http://localhost/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            #scope: name, email, profile_image
            scope: email
            client-name: Naver
          kakao:
            client-id: d022d183c0104d262e8d8f3ad5383630
            client-secret: GQ0sMOJKhBNa6etqzFQQfUGc1g6d9hVu
            redirect-uri: http://localhost/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email
            client-name: Kakao
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

--- # dev 설정
spring:
  config:
    activate:
      on-profile: "dev"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 797361358853-j9mpkpnq9bgrnmahi46dgkb5loufk5bg.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://devapp.how-taxing.com/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email
          naver:
            client-id: orG8AAE8iHfRSoiySAbv
            client-secret: DEn_pJGqup
            redirect-uri: http://devapp.how-taxing.com/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            #scope: name, email, profile_image
            scope: email
            client-name: Naver
          kakao:
            client-id: d022d183c0104d262e8d8f3ad5383630
            client-secret: GQ0sMOJKhBNa6etqzFQQfUGc1g6d9hVu
            redirect-uri: http://devapp.how-taxing.com/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email
            client-name: Kakao
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

--- # real 설정
spring:
  config:
    activate:
      on-profile: "real"
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 797361358853-j9mpkpnq9bgrnmahi46dgkb5loufk5bg.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: https://app.how-taxing.com/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope: profile, email
          naver:
            client-id: orG8AAE8iHfRSoiySAbv
            client-secret: DEn_pJGqup
            redirect-uri: https://app.how-taxing.com/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            #scope: name, email, profile_image
            scope: email
            client-name: Naver
          kakao:
            client-id: d022d183c0104d262e8d8f3ad5383630
            client-secret: GQ0sMOJKhBNa6etqzFQQfUGc1g6d9hVu
            redirect-uri: https://app.how-taxing.com/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: account_email
            client-name: Kakao
        provider:
          naver:
            authorization_uri: https://nid.naver.com/oauth2.0/authorize
            token_uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user_name_attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
